server:
  port: 8080

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # ✅ User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**

        # ✅ Booking Service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/v1/bookings/**

        # ✅ Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notifications/**

        # ✅ Payment Service
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/payments/**

        # ✅ Flight Service
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/v1/flights/**

        # ✅ Ticket Service
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/v1/tickets/**

      discovery:
        locator:
          enabled: true  # ✅ 서비스 자동 탐색 활성화

management:
  endpoints:
    web:
      exposure:
        include: prometheus  # Prometheus 메트릭 노출
  metrics:
    export:
      prometheus:
        enabled: true  # Prometheus 활성화


