server:
  port: 8080

spring:
  main:
    web-application-type: reactive  # 리액티브 설정 유지
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://config-server:8888  # Config Server 연결 추가
    gateway:
      discovery:
        locator:
          enabled: true  # 서비스 자동 탐색 활성화
      routes:
        # ✅ User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**

        # ✅ Booking Service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/v1/bookings/**

        # ✅ Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notifications/**

        # ✅ Payment Service
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/payments/**

        # ✅ Flight Service
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/v1/flights/**

        # ✅ Ticket Service
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/v1/tickets/**

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
    zipkin:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}
